### ISSUE TITLE
Spritesheets OutdoorsObjects.png is empty

### ISSUE THREAD

**Issue by josenerydev** [Apress/Devel-2D-Games-Unity#11]
In folder Chapter 4/Spritesheets OutdoorsObjects.png is empty.

**Comment by JaredHalpern** [comment]
![outdoorsobjects](https://user-images.githubusercontent.com/1355650/51934108-de39a400-23d0-11e9-8bb5-1c65e0aafd61.png)

**Comment by JaredHalpern** [comment]
I dropped it above and for some reason, GitHub doesn't like it. Hm.

**Comment by JaredHalpern** [comment]
Oh - you're using AESprite to view. I'm able to duplicate that on my machine as well. It's an issue with that software reading the file. Can you see it in Windows/File Explorer, and in Unity itself?

**Comment by JaredHalpern** [comment]
Updated errata/ README (https://github.com/Apress/Devel-2D-Games-Unity/blob/master/README.md#chapter-4) to give you credit as well. :) Thanks again.

**Comment by josenerydev** [comment]
Thanks your attention
