### ISSUE TITLE
GetQuadrant vars

### ISSUE THREAD

**Issue by VADS** [Apress/Devel-2D-Games-Unity#13]
On page 357, where you describe the implementation of the GetQuadrant() method, you seem to neither use the Vector2 var mousePosition not the playerPosition, if I see that correctly.

Really nice book though, I'm almost through! :)

**Comment by JaredHalpern** [comment]
Great eye! Thanks for filing this issue. I've updated the Eratta in the Readme and given you credit:
https://github.com/Apress/Devel-2D-Games-Unity#chapter-8-page-357
I'm so glad to hear you're enjoying the book! I'd love to see any games that you develop as a result of it. :-)
