### ISSUE TITLE
I can't see the coin on chapter 5.

### ISSUE THREAD

**Issue by pilaurent** [Apress/Devel-2D-Games-Unity#14]
Hi there, Hi Jared,
Great book so far, well explained !
But despite my efforts, i'm stuck at Chapter 5, where you show us how to create a coin object.

I can see it on the scene like [this](https://imageshack.com/i/plrysWAxp), but nothing appears when [playing](https://imageshack.com/i/plKHFUZbp) 

What i have done so far : 

1. checked that sorting layers are correctly ordered. (Default/Ground/Objects/Characters) ([here](https://imageshack.com/i/po1d5hq2p))

2. Sprite renderer:
- Sprite has been set to a coin image.
- Sorting Layer is **Objects**
- I imagine it is not relevant on this case, but Circle Collider 2D **"Is Trigger"** has been set.

3. I tried to change layer to be **ground** but unsuccessfully.

I'm sure i've done something wrong.
May you please give me some hints on how to make that coin appear ?

Regards,
Pierre

**Comment by JaredHalpern** [comment]
Hey Pierre - thanks for filing this issue and for the details. Would you be able to zip up your project and email it to me? I'd be happy to take a look after work. jared@jaredhalpern.com

**Comment by pilaurent** [comment]
Thank Jared for your help, everything is working fine.

For those who might be interested, i've completely forgot the Z axis in the **Inspector** / **transform**. Value has been set to **0**.
Also, Jared helped me reduce the spinning speed. ( **Double Click CoinController** / Clic on **CoinSpin** / Change the **Speed** value from 1 to **0.4** )

Regards !
