### ISSUE TITLE
Persistant Scriptable Objects

### ISSUE THREAD

**Issue by mprogers** [Apress/Devel-2D-Games-Unity#21]
In chapter 5, it says "As mentioned earlier, if we change any data in this Scriptable Object reference, we would change the data in the Scriptable Object asset itself, and those changes would remain when we stopped running our game". However, the Unity docs [seem to imply otherwise.](https://docs.unity3d.com/Manual/class-ScriptableObject.html. In particular, the line "In a deployed build, however, you can’t use ScriptableObjects to save data" seems relevant.

**Comment by JaredHalpern** [comment]
Hello and thank you for filing this issue. You're completely correct that they can't be used to save data. I should have clarified that statement further to emphasize the distinction between when running in the Editor versus a deployed build. I'll mention in the Errata just in case. Thanks again!

**Comment by JaredHalpern** [comment]
Updated the Errata and mentioned you @mprogers. Thank you.
