### ISSUE TITLE
Chapter 8 Weapon Class throwing nullreferenceexception on Vector3 mousePosition

### ISSUE THREAD

**Issue by Arnmazing23** [Apress/Devel-2D-Games-Unity#25]
IDK why it's throwing an exception on this line I've set the ammo prefab on this script and this Class is attached to the playerObject. The scripts Arc and Ammo are attached to ammoObject as well and everything looks the same. No ammo is being shot.

**Comment by JaredHalpern** [comment]
@Arnmazing23 Are you still having an issue with this? Lmk - happy to help.

**Comment by Arnmazing23** [comment]
No I figured it out, thanks!

**Comment by JaredHalpern** [comment]
Great to hear. Let me know if you have more questions.
