### ISSUE TITLE
Chapter3 which pictures are used for player-idle?

### ISSUE THREAD

**Issue by RenatiusvanSander** [Apress/Devel-2D-Games-Unity#26]
Would you please add the sprites for player-idle animation. I bought your book, but more and more are missing some sentences for the player animations. I cannot create player-idle for state machine figure 3-33 on page 76, because this animation is never explained and which pictures are to use to create animation player-idle. Would you please add the sprites for player-idle animation.

**Comment by JaredHalpern** [comment]
The player-idle images are the last two in the `Player32x32.png` sprite sheet, located in the Chapter 3 director [here](https://github.com/Apress/Devel-2D-Games-Unity/blob/master/Chapter%203/Spritesheets/Player32x32.png). Hope that helps.
