### ISSUE TITLE
Null Reference Exception thrown but is set to an instance of an object

### ISSUE THREAD

**Issue by Arnmazing23** [Apress/Devel-2D-Games-Unity#28]
I accidentally deleted RPGGameManager Prefab and I recreated it. Now I'm getting a null reference Exception but I check the code and it is set to an instance of the object. I check virtual camera when game is running and virtual camera isn't following the player even when the tag is set to "VirtualCamera". I checked all the prefabs in inspector and everything is correctly attached. RPGGameManager has PlayerSpawnPoint and RPGCameraManager, PlayerSpawnPoint has PlayerObject attached, RPGCameraManager has the script attached to it.

**Comment by JaredHalpern** [comment]
Seems like you were able to resolve this.
Thanks for closing out the issue!

**Comment by Arnmazing23** [comment]
Yes!
