### ISSUE TITLE
HeartGameObject not visible (with solution)

### ISSUE THREAD

**Issue by RenatiusvanSander** [Apress/Devel-2D-Games-Unity#29]
I share this solution with others. Newer Unity versions place the Haeart item of chapter five above or below the tiles. The camera cannot catch that. change z position to zero and everything is fine.

**Comment by JaredHalpern** [comment]
Thank you so much for this comment. Even though it's not an error, I will make a note of it in the README so that other readers can benefit from this pitfall.

**Comment by RenatiusvanSander** [comment]
Hello Jared, this happens when you position a game object. The z-position seems to be set randomly. Thanks you add this. Me took finding the solution an hour. Hope this help others.

Best regards Remy

**Comment by JaredHalpern** [comment]
I've added this to a newly created section, General Notes, and given you credit -- https://github.com/Apress/Devel-2D-Games-Unity/blob/master/README.md#general-notes
