### ISSUE TITLE
No player-idle clip instructions

### ISSUE THREAD

**Issue by omundy** [Apress/Devel-2D-Games-Unity#3]
On page 76 the book says to make a transition to the player-idle state. But there are no instructions to make this clip so it doesn't exist for to make the transition.

**Comment by JaredHalpern** [comment]
Thanks so much for pointing this out @omundy - I really appreciate it. Corrected in PR: https://github.com/Apress/Devel-2D-Games-Unity/pull/5. The master `README` now contains instructions on how to create the missing animation clip. Please let me know if you notice anything else, or have feedback. My email address is my first name @ my first and last name + .com. Thanks again.
