### ISSUE TITLE
[Grammar/Punctuation] - "follow" vs "follows" (Ch. 4)

### ISSUE THREAD

**Issue by profjpbaugh** [Apress/Devel-2D-Games-Unity#31]
Top of p. 106, first paragraph, "... and we'll use a tool called Cinemachine to make the Camera follows the Player as he walks."

Suggest change to "... make the Camera **follow** the Player as he walks."  
or
"make **sure** the Camera follows the Player as he walks.

**Comment by JaredHalpern** [comment]
Thank you for mentioning. If we do a second edition of the book, I'll incorporate this correction.
