### ISSUE TITLE
Still In Tutorial Hell

### ISSUE THREAD

**Issue by ghost** [Apress/Devel-2D-Games-Unity#47]
This book teach me how to make games.
but the only problem I have is that..
I code or develope a game like a beginner.
Obviously I'm beginner..
I developing my own games and when I'm writing codes or develope game codes. I'm always following your code step by step
 Instead of writing all the code.
For example i write the code and finish the movementcontroller.
instead of writing the code step by step.

SORRY FOR BAD ENGLISH

**Comment by Brog125** [comment]
I tried to search a unity game development timelapse in unity in YouTube.
And I don't find anything. 
I really want know how the professional do or develope codes
